module.exports = {
  layout1: ['dist/layout1/*'],
  layoutrtl1: ['dist/layoutrtl1/*'],
  layout2: ['dist/layout2/*'],
  layoutrtl2: ['dist/layoutrtl2/*'],
  layout3: ['dist/layout3/*'],
  layoutrtl3: ['dist/layoutrtl3/*'],
  layout4: ['dist/layout4/*'],
  layoutrtl4: ['dist/layoutrtl4/*'],
  layout5: ['dist/layout5/*'],
  layoutrtl5: ['dist/layoutrtl5/*'],
  layout6: ['dist/layout6/*'],
  layoutrtl6: ['dist/layoutrtl6/*'],
  bowerfolder: ['dist/bower_components/*'],
};
