module.exports = {
    layout1: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layout1/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layout1/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layout1/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layout1/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layout1/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/templates', dest: "dist/layout1/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/api', dest: "dist/layout1/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/i18n', dest: "dist/layout1/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/images', dest: "dist/layout1/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/config', dest: "dist/layout1/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/directives', dest: "dist/layout1/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/controllers', dest: "dist/layout1/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/filters', dest: "dist/layout1/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/views', dest: "dist/layout1/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/css/themes', dest: "dist/layout1/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layout1/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-1/STANDARD/master/_index.min.html', dest: 'dist/layout1/index.html' },
            { src: 'LAYOUT-1/STANDARD/favicon.ico', dest: 'dist/layout1/favicon.ico' },
            { src: 'LAYOUT-1/STANDARD/upload.php', dest: 'dist/layout1/upload.php' }
        ]
    },
    layoutrtl1: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layoutrtl1/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layoutrtl1/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layoutrtl1/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layoutrtl1/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layoutrtl1/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/templates', dest: "dist/layoutrtl1/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/api', dest: "dist/layoutrtl1/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/i18n', dest: "dist/layoutrtl1/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/images', dest: "dist/layoutrtl1/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/config', dest: "dist/layoutrtl1/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/directives', dest: "dist/layoutrtl1/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/controllers', dest: "dist/layoutrtl1/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/filters', dest: "dist/layoutrtl1/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/views', dest: "dist/layoutrtl1/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/css/themes', dest: "dist/layoutrtl1/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layoutrtl1/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-1/RTL/master/_index.min.html', dest: 'dist/layoutrtl1/index.html' },
            { src: 'LAYOUT-1/RTL/favicon.ico', dest: 'dist/layoutrtl1/favicon.ico' },
            { src: 'LAYOUT-1/RTL/upload.php', dest: 'dist/layoutrtl1/upload.php' }
        ]
    },
    layout2: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layout2/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layout2/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layout2/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layout2/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layout2/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/templates', dest: "dist/layout2/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/api', dest: "dist/layout2/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/i18n', dest: "dist/layout2/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/images', dest: "dist/layout2/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/config', dest: "dist/layout2/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/directives', dest: "dist/layout2/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/controllers', dest: "dist/layout2/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/filters', dest: "dist/layout2/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/views', dest: "dist/layout2/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/css/themes', dest: "dist/layout2/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layout2/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-2/STANDARD/master/_index.min.html', dest: 'dist/layout2/index.html' },
            { src: 'LAYOUT-2/STANDARD/favicon.ico', dest: 'dist/layout2/favicon.ico' },
            { src: 'LAYOUT-2/STANDARD/upload.php', dest: 'dist/layout2/upload.php' }
        ]
    },
    layoutrtl2: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layoutrtl2/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layoutrtl2/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layoutrtl2/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layoutrtl2/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layoutrtl2/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/templates', dest: "dist/layoutrtl2/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/api', dest: "dist/layoutrtl2/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/i18n', dest: "dist/layoutrtl2/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/images', dest: "dist/layoutrtl2/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/config', dest: "dist/layoutrtl2/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/directives', dest: "dist/layoutrtl2/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/controllers', dest: "dist/layoutrtl2/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/filters', dest: "dist/layoutrtl2/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/views', dest: "dist/layoutrtl2/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/css/themes', dest: "dist/layoutrtl2/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layoutrtl2/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-2/RTL/master/_index.min.html', dest: 'dist/layoutrtl2/index.html' },
            { src: 'LAYOUT-2/RTL/favicon.ico', dest: 'dist/layoutrtl2/favicon.ico' },
            { src: 'LAYOUT-2/RTL/upload.php', dest: 'dist/layoutrtl2/upload.php' }
        ]
    },
    layout3: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layout3/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layout3/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layout3/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layout3/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layout3/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/templates', dest: "dist/layout3/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/api', dest: "dist/layout3/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/i18n', dest: "dist/layout3/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/images', dest: "dist/layout3/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/config', dest: "dist/layout3/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/directives', dest: "dist/layout3/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/controllers', dest: "dist/layout3/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/filters', dest: "dist/layout3/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/views', dest: "dist/layout3/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/css/themes', dest: "dist/layout3/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layout3/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-3/STANDARD/master/_index.min.html', dest: 'dist/layout3/index.html' },
            { src: 'LAYOUT-3/STANDARD/favicon.ico', dest: 'dist/layout3/favicon.ico' },
            { src: 'LAYOUT-3/STANDARD/upload.php', dest: 'dist/layout3/upload.php' }
        ]
    },
    layoutrtl3: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layoutrtl3/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layoutrtl3/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layoutrtl3/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layoutrtl3/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layoutrtl3/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/templates', dest: "dist/layoutrtl3/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/api', dest: "dist/layoutrtl3/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/i18n', dest: "dist/layoutrtl3/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/images', dest: "dist/layoutrtl3/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/config', dest: "dist/layoutrtl3/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/directives', dest: "dist/layoutrtl3/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/controllers', dest: "dist/layoutrtl3/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/filters', dest: "dist/layoutrtl3/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/views', dest: "dist/layoutrtl3/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/css/themes', dest: "dist/layoutrtl3/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layoutrtl3/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-3/RTL/master/_index.min.html', dest: 'dist/layoutrtl3/index.html' },
            { src: 'LAYOUT-3/RTL/favicon.ico', dest: 'dist/layoutrtl3/favicon.ico' },
            { src: 'LAYOUT-3/RTL/upload.php', dest: 'dist/layoutrtl3/upload.php' }
        ]
    },
    layout4: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layout4/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layout4/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layout4/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layout4/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layout4/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/templates', dest: "dist/layout4/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/api', dest: "dist/layout4/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/i18n', dest: "dist/layout4/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/images', dest: "dist/layout4/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/config', dest: "dist/layout4/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/directives', dest: "dist/layout4/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/controllers', dest: "dist/layout4/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/filters', dest: "dist/layout4/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/views', dest: "dist/layout4/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/css/themes', dest: "dist/layout4/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layout4/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-4/STANDARD/master/_index.min.html', dest: 'dist/layout4/index.html' },
            { src: 'LAYOUT-4/STANDARD/favicon.ico', dest: 'dist/layout4/favicon.ico' },
            { src: 'LAYOUT-4/STANDARD/upload.php', dest: 'dist/layout4/upload.php' }
        ]
    },
    layoutrtl4: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layoutrtl4/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layoutrtl4/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layoutrtl4/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layoutrtl4/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layoutrtl4/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/templates', dest: "dist/layoutrtl4/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/api', dest: "dist/layoutrtl4/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/i18n', dest: "dist/layoutrtl4/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/images', dest: "dist/layoutrtl4/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/config', dest: "dist/layoutrtl4/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/directives', dest: "dist/layoutrtl4/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/controllers', dest: "dist/layoutrtl4/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/filters', dest: "dist/layoutrtl4/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/views', dest: "dist/layoutrtl4/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/css/themes', dest: "dist/layoutrtl4/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layoutrtl4/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-4/RTL/master/_index.min.html', dest: 'dist/layoutrtl4/index.html' },
            { src: 'LAYOUT-4/RTL/favicon.ico', dest: 'dist/layoutrtl4/favicon.ico' },
            { src: 'LAYOUT-4/RTL/upload.php', dest: 'dist/layoutrtl4/upload.php' }
        ]
    },
    layout5: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layout5/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layout5/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layout5/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layout5/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layout5/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/templates', dest: "dist/layout5/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/api', dest: "dist/layout5/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/i18n', dest: "dist/layout5/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/images', dest: "dist/layout5/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/config', dest: "dist/layout5/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/directives', dest: "dist/layout5/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/controllers', dest: "dist/layout5/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/filters', dest: "dist/layout5/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/views', dest: "dist/layout5/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/css/themes', dest: "dist/layout5/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layout5/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-5/STANDARD/master/_index.min.html', dest: 'dist/layout5/index.html' },
            { src: 'LAYOUT-5/STANDARD/favicon.ico', dest: 'dist/layout5/favicon.ico' },
            { src: 'LAYOUT-5/STANDARD/upload.php', dest: 'dist/layout5/upload.php' }
        ]
    },
    layoutrtl5: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layoutrtl5/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layoutrtl5/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layoutrtl5/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layoutrtl5/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layoutrtl5/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/templates', dest: "dist/layoutrtl5/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/api', dest: "dist/layoutrtl5/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/i18n', dest: "dist/layoutrtl5/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/images', dest: "dist/layoutrtl5/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/config', dest: "dist/layoutrtl5/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/directives', dest: "dist/layoutrtl5/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/controllers', dest: "dist/layoutrtl5/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/filters', dest: "dist/layoutrtl5/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/views', dest: "dist/layoutrtl5/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/css/themes', dest: "dist/layoutrtl5/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layoutrtl5/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-5/RTL/master/_index.min.html', dest: 'dist/layoutrtl5/index.html' },
            { src: 'LAYOUT-5/RTL/favicon.ico', dest: 'dist/layoutrtl5/favicon.ico' },
            { src: 'LAYOUT-5/RTL/upload.php', dest: 'dist/layoutrtl5/upload.php' }
        ]
    },
    layout6: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layout6/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layout6/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layout6/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layout6/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layout6/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/templates', dest: "dist/layout6/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/api', dest: "dist/layout6/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/i18n', dest: "dist/layout6/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/images', dest: "dist/layout6/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/config', dest: "dist/layout6/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/directives', dest: "dist/layout6/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/controllers', dest: "dist/layout6/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/filters', dest: "dist/layout6/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/views', dest: "dist/layout6/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/css/themes', dest: "dist/layout6/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layout6/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-6/STANDARD/master/_index.min.html', dest: 'dist/layout6/index.html' },
            { src: 'LAYOUT-6/STANDARD/favicon.ico', dest: 'dist/layout6/favicon.ico' },
            { src: 'LAYOUT-6/STANDARD/upload.php', dest: 'dist/layout6/upload.php' }
        ]
    },
    layoutrtl6: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "dist/layoutrtl6/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "dist/layoutrtl6/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "dist/layoutrtl6/assets/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "dist/layoutrtl6/assets/css/fonts" },
            { expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "dist/layoutrtl6/assets/flags" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/templates', dest: "dist/layoutrtl6/templates" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/api', dest: "dist/layoutrtl6/assets/api" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/i18n', dest: "dist/layoutrtl6/assets/i18n" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/images', dest: "dist/layoutrtl6/assets/images" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/config', dest: "dist/layoutrtl6/assets/js/config" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/directives', dest: "dist/layoutrtl6/assets/js/directives" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/controllers', dest: "dist/layoutrtl6/assets/js/controllers" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/filters', dest: "dist/layoutrtl6/assets/js/filters" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/views', dest: "dist/layoutrtl6/assets/views" },
            { expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/css/themes', dest: "dist/layoutrtl6/assets/css/themes" },
            { src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest: 'dist/layoutrtl6/assets/css/ajax-loader.gif' },
            { src: 'LAYOUT-6/RTL/master/_index.min.html', dest: 'dist/layoutrtl6/index.html' },
            { src: 'LAYOUT-6/RTL/favicon.ico', dest: 'dist/layoutrtl6/favicon.ico' },
            { src: 'LAYOUT-6/RTL/upload.php', dest: 'dist/layoutrtl6/upload.php' }
        ]
    },
    bowerfolder: {
        files: [
            { expand: true, src: "**", cwd: 'bower_components', dest: "dist/bower_components" }
        ]
    }
};
